---
title: "surivial model"
output: html_document
date: "2024-02-02"
---
#install the packages and library
```{r setup, include=FALSE}
#install the package
library(survival)
library(survminer)
library(coxme)
```
#read the file
```{r}
db<-read.csv(file = '.../RTime_species.csv',sep=";",stringsAsFactors=T)
levels(db$LU)
db$LU<-
  factor(db$LU,c("Primary","Secondary","Plantation-Pasture","Cropland-Urban"))
```

##birds
```{r}
bird.mod<- survfit(Surv(sp_RT,Alien.presence ,type="right") ~ LU, data=db[db$taxa=="Birds",])
bird<-ggsurvplot(bird.mod,
          palette = c("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"),
          fun = "event",
          conf.int = TRUE,
          pval=F,
          legend = "none",
          ylab = c(" "), 
          xlab = c(" "),
          font.tickslab = c(14),
          xlim = c(0, 212),
          surv.median.line = "hv", 
          ggtheme = theme_linedraw())$plot

bird

ggsave(bird,filename = '.../bird.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)
```
#mammals
```{r}
db.mam<-db[db$taxa=="Mammals",]
db.mam<-db.mam %>%filter(LU != "Cropland-Urban") %>% droplevels()
mam.mod<- survfit(Surv(sp_RT,Alien.presence ,type="right") ~ LU, data=db.mam)
mam.sp<-ggsurvplot(mam.mod,
          palette = c("#0000FFFF","#00FFFFFF","darkgoldenrod3"), 
          fun="event",
          conf.int = TRUE,
          pval=F,
          legend = "none",
          ylab = c(" "), 
          xlab = c(" "),
          font.tickslab = c(14),
          xlim = c(0, 212),
          surv.median.line = "hv" ,
          ggtheme = theme_linedraw())$plot

mam.sp
ggsave(mam.sp,filename = '.../mammals.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)
```
#vascular plants
```{r}
plant.mod<- survfit(Surv(sp_RT,Alien.presence ,type="right") ~ LU, data=db[db$taxa=="Vascular plants",])
plant.sp<-ggsurvplot(plant.mod,
          palette = c("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"),
          fun = "event",
          conf.int = TRUE,
          pval=F,
          legend = "none",
          ylab = c(" "), 
          xlab = c(" "),
          font.tickslab = c(14),
          xlim = c(0, 212),
          surv.median.line = "hv", 
          ggtheme = theme_linedraw())$plot

plant.sp

ggsave(plant.sp,filename = '.../plant.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)
```
#all
```{r}
all.mod<- survfit(Surv(sp_RT,Alien.presence ,type="right") ~ LU, data=db)
all.sp<-ggsurvplot(all.mod,
          palette = c("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"),
          fun = "event",
          conf.int = TRUE,
          pval=F,
          legend = "none",
          ylab = c(" "), 
          xlab = c(" "),
          font.tickslab = c(14),
          xlim = c(0, 212),
          surv.median.line = "hv", 
          ggtheme = theme_linedraw())$plot

all.sp

ggsave(all.sp,filename = '.../all.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)
```



