---
title: "alien occurrence"
output: html_document
date: "2024-02-02"
---

```{r}
#library(afex)
library(lme4)
library(data.table)
library(emmeans)
library(multcomp)
library(lme4)
library(ggplot2)
library(tidyverse)
library(DHARMa)# testDispersion
#install.packages("glmmTMB", dependencies = TRUE, INSTALL_opts = c("--no-lock"))
library(glmmTMB)
library(ggeffects)
#install.packages("ggiraphExtra")
library(ggiraphExtra)
require(ggiraph)
require(ggiraphExtra)
require(plyr)
require(moonBook)
library(dplyr)
library(tidyr)
#library(predict3d)
#install.packages("MASS")
library(MASS)
#install.packages("devtools")
#devtools::install_github("cardiomoon/ggiraphExtra")
library(moonBook)
library(mlbench)
```
#import the data
```{r}
data.new<- read.csv(file = ".../RTime_region.csv", sep=';')
```
#birds
```{r}
full1<-glmer(Alien.presence~LU*R.c18.mean+(1|SS/SSB),data = data.new[data.new$taxa=="Birds",] , 
               family = binomial, control = glmerControl(optimizer = "bobyqa" , 
                                                         optCtrl = list(maxfun = 1e5)),nAGQ = 1 )
model.data<-data.frame(ggpredict(full1, terms = c("R.c18.mean[all]","LU")))
names(model.data)[1:6]<-c("Invasion_time","Alien_incidence", "se", "conf.low","conf.high", "LU" )
model.data$LU<-as.factor(model.data$LU)

birds_a<-  ggplot(model.data , aes(Invasion_time, Alien_incidence,color=LU))+
  scale_color_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_fill_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_y_continuous(name="Alien incidence",limits=c(0,1.0),breaks=seq(0,1.0,0.25))+
  scale_x_continuous(name="Alien residence time (years)",
                     limits=c(0,133),breaks=seq(0,133,40))+
  geom_line(aes(color = LU),size=1.2)+
  geom_ribbon(aes(ymin = conf.low , ymax = conf.high,colour = factor(LU), 
                  fill = factor(LU)),alpha=0.2,linetype=0)+
  annotate("text", x=130, y=0.07, label= "***",size=8,color="darkgoldenrod3") +
  annotate("text", x=130, y=0.4, label= "**",size=8,color="#00FFFFFF") +  
  annotate("text", x=130, y=0.75, label= "***",size=8,color="#FF0000FF") +    
  theme_linedraw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14) ,
        axis.text.y = element_text(colour = "black",  size = 14),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "vertical",
        legend.position = "none")
birds_a
```
```{r}
data.new.b<-data.new[data.new$taxa=="Birds",]

birds_b<-
  ggplot(data.new.b, aes(x=LU, y=R.c18.mean),color=LU) +
  geom_violin(aes(color = LU),trim=FALSE,width=1.2, fill='white')+
  geom_boxplot(width=0.2) + 
  scale_color_manual(values =c ("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"))+
  scale_y_continuous(limits=c(-10,140),breaks=seq(0,140,40))+
  labs(y= "Residence time")+
  theme_classic()+
  theme(panel.grid.major.x = element_blank() , 
        axis.line.x = element_line(size = 0.22,color="black"),
        axis.line.y = element_line(size = 0.2),
  axis.ticks.length=unit(0.08,"inch"),
  axis.text.x = element_blank() ,
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  legend.position="none")
birds_b
#combine two plots inset into one
library(patchwork)
birds<-
  birds_a +
  inset_element(birds_b, left = 0.02, bottom = 0.55, right = 0.55, top = 0.95)
birds
ggsave(birds,filename='.../fig2b.new.tiff',compression='lzw',width = 6.0,height =4,dpi=200)
```
#mammals
```{r}
full<-glmer(Alien.presence~LU+R.c18.mean+(1|SS/SSB),
             data = data.new[data.new$taxa=="Mammals"&data.new$LU!="Cropland-Urban",] , 
             family = binomial, control = glmerControl(optimizer = "bobyqa" ,
                                                         optCtrl = list(maxfun = 1e5)),nAGQ = 1 )

model.data<-data.frame(ggpredict(full1, terms = c("R.c18.mean[all]","LU")))
names(model.data)[1:6]<-c("Invasion_time","Alien_incidence", "se", "conf.low","conf.high", "LU" )
model.data$LU<-as.factor(model.data$LU)

mam_a<-  ggplot(model.data , aes(Invasion_time, Alien_incidence,color=LU))+
  scale_color_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_fill_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_y_continuous(name="Alien incidence",limits=c(0,1.0),breaks=seq(0,1.0,0.25))+
  scale_x_continuous(name="Alien residence time (years)",
                     limits=c(0,123),breaks=seq(0,123,40))+
  geom_line(aes(color = LU),size=1.2)+
  geom_ribbon(aes(ymin = conf.low , ymax = conf.high,colour = factor(LU), 
                  fill = factor(LU)),alpha=0.2,linetype=0)+
  theme_linedraw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14) ,
        axis.text.y = element_text(colour = "black",  size = 14),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "vertical",
        legend.position = "none")
mam_a
```

```{r}
data.new.b<-data.new[data.new$taxa=="Mammals"&data.new$LU!="Cropland-Urban",]

mammals_b<-
  ggplot(data.new.b, aes(x=LU, y=R.c18.mean)) +
  geom_violin(aes(fill = LU),trim=FALSE,width=1.3)+
  geom_boxplot(width=0.1) + 
  scale_fill_manual(values =c ("#0000FFFF","#00FFFFFF","darkgoldenrod3"))+
  scale_y_continuous(limits=c(-10,150),breaks=seq(0,150,40))+
  labs(y= "Residence time")+

  theme_classic()+
  theme(panel.grid.major.x = element_blank() , 
  axis.ticks.length=unit(0.08,"inch"),
  axis.text.x = element_blank() ,
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  legend.position="none")
mammals_b
#combine two plots inset into one
library(patchwork)
mammals<-
  mam_a +
  inset_element(mammals_b, left = 0.02, bottom = 0.55, right = 0.55, top = 0.95)
mammals
ggsave(mammals,filename='.../fig2a.tiff',compression='lzw',width = 6.0,height =4,dpi=200)
```
#plants
```{r}
full<-glmer(Alien.presence~LU*R.c18.mean+(1|SS/SSB),
             data = data.new[data.new$taxa=="Vascular plants",] , 
             family = binomial, control = glmerControl(optimizer = "bobyqa" ,
                                                         optCtrl = list(maxfun = 1e5)),nAGQ = 1 )
model.data<-data.frame(ggpredict(full, terms = c("R.c18.mean[all]","LU")))
names(model.data)[1:6]<-c("Invasion_time","Alien_incidence", "se", "conf.low","conf.high", "LU" )
model.data$LU<-as.factor(model.data$LU)


plant_a<-
  ggplot(model.data , aes(Invasion_time, Alien_incidence,color=LU))+
 
  scale_color_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_fill_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_y_continuous(name="Alien incidence",limits=c(0,1.0),breaks=seq(0,1.0,0.25))+
  scale_x_continuous(name="Alien residence time (years)",
                     limits=c(0,166),breaks=seq(0,166,50))+
  geom_line(aes(color = LU),size=1.2)+
  geom_ribbon(aes(ymin = conf.low , ymax = conf.high,colour = factor(LU), fill = factor(LU)),alpha=0.2,linetype=0)+
  annotate("text", x=165, y=0.66, label= "***",size=8,color="#00FFFFFF") + 
  annotate("text", x=165, y=0.69, label= "***",size=8,color="darkgoldenrod3") +
  annotate("text", x=165, y=0.72, label= "***",size=8,color="#FF0000FF") + 
  theme_linedraw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14) ,
        axis.text.y = element_text(colour = "black",  size = 14),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "vertical",
        legend.position = "none")
plant_a

```

```{r}
data.new.b<-data.new[data.new$taxa=="Vascular plants",]

plant_b<-
  ggplot(data.new.b, aes(x=LU, y=R.c18.mean),color=LU) +
  geom_violin(aes(color = LU),trim=FALSE,width=1.2, fill='white')+
  geom_boxplot(width=0.2) + 
  scale_color_manual(values =c ("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"))+
  scale_y_continuous(limits=c(-10,170),breaks=seq(0,170,50))+
  labs(y= "Residence time")+
  theme_classic()+
  theme(panel.grid.major.x = element_blank() , 
        axis.line.x = element_line(size = 0.22,color="black"),
        axis.line.y = element_line(size = 0.2),
  axis.ticks.length=unit(0.08,"inch"),
  axis.text.x = element_blank() ,
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  legend.position="none")
plant_b
#combine two plots inset into one
library(patchwork)
plant<-
  plant_a +
  inset_element(plant_b, left = 0.02, bottom = 0.55, right = 0.55, top = 0.95)
plant

ggsave(plant,filename = '.../fig2d.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)
```

```{r}
full<-glmer(Alien.presence~LU+R.c18.mean+(1|SS/SSB/taxa),data = data.new , 
             family = binomial, control = glmerControl(optimizer = "bobyqa" ,
                                                         optCtrl = list(maxfun = 1e5)),nAGQ = 1 )
model.data<-data.frame(ggpredict(full2, terms = c("R.c18.mean[all]","LU")))
names(model.data)[1:6]<-c("Invasion_time","Alien_incidence", "se", "conf.low","conf.high", "LU" )
model.data$LU<-as.factor(model.data$LU)

all_a<-
  ggplot(model.data , aes(Invasion_time, Alien_incidence))+
 
  scale_color_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_fill_manual(values = c("#0000FFFF","#00FFFFFF","darkgoldenrod3",
                                "#FF0000FF"),name="LU-types")+
  scale_y_continuous(name="Alien incidence",limits=c(0,1.0),breaks=seq(0,1.0,0.25))+
  scale_x_continuous(name="Alien residence time (years)",
                     limits=c(0,163),breaks=seq(0,160,50))+
  annotate("text", x=160, y=0.95, label= "***",size=8,color="#FF0000FF") + 
 
  geom_line(aes(color = LU),size=1.2)+
  geom_ribbon(aes(ymin = conf.low , ymax = conf.high,colour = factor(LU), 
                  fill = factor(LU)),alpha=0.2,linetype=0)+
  theme_linedraw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14) ,
        axis.text.y = element_text(colour = "black",  size = 14),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "vertical",
        legend.position = "none")
all_a
```

```{r}
data.new.b<-data.new


all_b<-
  ggplot(data.new.b, aes(x=LU, y=R.c18.mean),color=LU) +
  geom_violin(aes(color = LU),trim=FALSE,width=1.2, fill='white')+
  geom_boxplot(width=0.2) + 
  scale_color_manual(values =c ("#0000FFFF","#00FFFFFF","darkgoldenrod3", "#FF0000FF"))+
  scale_y_continuous(limits=c(-10,170),breaks=seq(0,170,50))+
  labs(y= "Residence time")+
  theme_classic()+
  theme(panel.grid.major.x = element_blank() , 
        axis.line.x = element_line(size = 0.22,color="black"),
        axis.line.y = element_line(size = 0.2),
  axis.ticks.length=unit(0.08,"inch"),
  axis.text.x = element_blank() ,
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  legend.position="none")
all_b
#combine two plots inset into one
library(patchwork)
all<-
  all_a +
  inset_element(all_b, left = 0.02, bottom = 0.55, right = 0.55, top = 0.95)
all

ggsave(all,filename = '.../fig2d.tiff',compression='lzw', width = 6.0,height = 4,dpi=200)

```
